# https://rust-lang.github.io/rustfmt/?version=master&search=
unstable_features = true

# Stable
use_field_init_shorthand = true
use_try_shorthand = true

# Unstable
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
overflow_delimited_expr = true
hex_literal_case = "Upper"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
wrap_comments = true


# ? To consider
# version = "Two"
# enum_discrim_align_threshold = 20
# struct_field_align_threshold = 20
# inline_attribute_width = 0
# short_array_element_width_threshold = 20
